name: QA Deployment
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm install
      - name: Create Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  deploy-to-firebase:
    name: Deploy to Firebase QA channel
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Download Production Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist     
      - name: Disable existing previews
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:delete ${{ vars.APP_NAME }}-qa --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 
      - name: Deploy to Firebase
        if: success() || failure()
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy ${{ vars.APP_NAME }}-qa
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
